---
title: "Combine LECS datasets"
format: html
editor: source
---

Combine LECS Parquet files

NO LONGER USED

parquet files are now written partitioned by download initially.


```{r}
#| warning: false
#| message: false

library(arrow)
library(tidyverse)
library(mlabtools)

theme_set(theme_bw())
options(digits.secs=3)
```

## Combine all data and save

connect to all adv data

```{r}
data_dir <- "data/processed/"

# adv data
files <- c(
  #"lander/lecs_adv_data_2023-07-24.parquet", 
  "surface/lecs_adv_data_2023-09-05.parquet", 
  "surface/lecs_adv_data_2023-11-15.parquet",
  "surface/lecs_adv_data_2024-01-23.parquet",
  "surface/lecs_adv_data_2024-02-28.parquet",
  "surface/lecs_adv_data_2024-05-14.parquet")
paths <- file.path(paste0(data_dir, files))
adv_data_all_list <- map(paths, open_dataset)
adv_data_all <- adv_data_all_list |> 
  map(collect) |> 
  bind_rows()

write_dataset(adv_data_all, paste0(data_dir, "adv_all.parquet"))

# status data
files <- c(
  #"lander/lecs_status_2023-07-24.parquet", 
  "surface/lecs_status_2023-09-05.parquet", 
  "surface/lecs_status_2023-11-15.parquet",
  "surface/lecs_status_2024-01-23.parquet",
  "surface/lecs_status_2024-02-28.parquet",
  "surface/lecs_status_2024-05-14.parquet")
paths <- file.path(paste0(data_dir, files))
status_all_list <- map(paths, open_dataset)
status_all <- status_all_list |> 
  map(collect) |> 
  bind_rows()
write_dataset(status_all, paste0(data_dir, "status_all.parquet"))

# met data
files <- c(
  #"lander/lecs_met_2023-07-24.parquet", 
  "surface/lecs_met_2023-09-05.parquet", 
  "surface/lecs_met_2023-11-15.parquet",
  "surface/lecs_met_2024-01-23.parquet",
  "surface/lecs_met_2024-02-28.parquet",
  "surface/lecs_met_2024-05-14.parquet")
paths <- file.path(paste0(data_dir, files))
met_all_list <- map(paths, open_dataset)
met_all <- met_all_list |> 
  map(collect) |> 
  bind_rows()
write_dataset(met_all, paste0(data_dir, "met_all.parquet"))
```

```{r}
status <- open_dataset(paste0(data_dir, "status_all.parquet"))
```

