---
title: "LECS EDA for filtering data"
format: html
editor: source
---

Find bad sections in data and limits for value-based filtering.

```{r}
library(arrow)
library(tidyverse)
library(dygraphs)

options(digits.secs = 6)

data_dir <- "data/processed/surface"
```

Open dataset

```{r}
ds <- open_dataset(file.path(data_dir, "lecs_adv_data.parquet"))
```


```{r}
names(ds)
```


```{r}
nrow(ds)
```


```{r}
summarize(ds, start = min(timestamp), end = max(timestamp)) %>% collect()
```


```{r}
ds
```

Duplicates?

```{r}
ds |> 
  filter(timestamp > "2023-08-05 00:00:00",
         timestamp < "2023-08-06 00:00:00") |> 
  group_by(timestamp) |> 
  summarize(n = n()) |> 
  filter(n > 1) |> 
  collect()
```
Open minute averages to get proper ranges. Need to create hour or minute average dataset to do this

```{r}
df_min <- ds |> 
  mutate(timestamp = floor_date(timestamp, "minute")) |> 
  group_by(timestamp) |> 
  summarise(across(everything(), 
                   ~ mean(.x, na.rm = TRUE))) |> 
  ungroup() |> 
  collect()
```

```{r}
df_min |> 
  ggplot(aes(timestamp, temp)) +
  geom_line()
```

```{r}
df_min |> 
  ggplot(aes(timestamp, ox_umol_l)) +
  geom_line()
```

```{r}
df_min |> 
  select(timestamp, pH) |> 
  dygraph()
```

```{r}
df_min |> 
  select(timestamp, ox_umol_l) |> 
  dygraph()
```

```{r}
df_min |> 
  ggplot(aes(timestamp, pH)) +
  geom_line()
```

```{r}
ds |> 
  glimpse()
```

```{r}
df_min |> 
  select(timestamp, pressure) |> 
  dygraph()
```

# Check filtered data

```{r}
ds_filt <- open_dataset(file.path(data_dir, "lecs_adv_filt.parquet"))
```


```{r}
nrow(ds_filt)
```


```{r}
summarize(ds_filt, start = min(timestamp), end = max(timestamp)) %>% collect()
```

Not sure what causes these more recent duplicates.
Calculate duplicate fraction over a time period


```{r}
dsf1 <- ds_filt |> 
  filter(timestamp > "2023-01-01 00:00:00",
         timestamp < "2023-12-01 00:00:00") 

dss1 <- dsf1 |> 
  group_by(timestamp) |> 
  summarize(n = n()) |> 
  filter(n > 1) |> 
  collect()

dsf2 <- ds_filt |> 
  filter(timestamp > "2023-12-01 00:00:00",
         timestamp < "2024-06-01 00:00:00") 

dss2 <- dsf2 |> 
  group_by(timestamp) |> 
  summarize(n = n()) |> 
  filter(n > 1) |> 
  collect()

dsf3 <- ds_filt |> 
  filter(timestamp > "2024-06-01 00:00:00",
         timestamp < "2024-10-01 00:00:00") 

dss3 <- dsf3 |> 
  group_by(timestamp) |> 
  summarize(n = n()) |> 
  filter(n > 1) |> 
  collect()

dss <- bind_rows(dss1, dss2, dss3)

ggplot(dss, aes(timestamp)) +
  geom_histogram(binwidth = 3600 * 24)
```
