---
title: "filter LECS data"
format: html
editor: source
---

Filter all bad data out of raw dataset

Runs after processing csv files to a single Arrow dataset

Run before pH calibration.

```{r}
library(arrow)
library(duckdb)
library(tidyverse)
library(dygraphs)

data_dir <- "data/processed/surface"
con <- dbConnect(duckdb(), dbdir = "my-db.duckdb", read_only = FALSE)
```

Open dataset

```{r}
ds <- open_dataset(file.path(data_dir, "lecs_adv_data.parquet"))
```

# Filter

```{r}
ds_filt <- ds |> 
  to_duckdb(con = con) |> 
  filter(#!(timestamp > "2023-06-23 13:00:00" & timestamp < "2023-06-26 11:00:00"),
         #!(timestamp > "2023-07-11 12:45:00" & timestamp < "2023-07-20 20:15:00"),
         !(timestamp > "2023-07-24 16:49:00" & timestamp < "2023-07-25 00:15:00"),
         !(timestamp > "2023-08-23 14:15:00" & timestamp < "2023-08-23 16:10:00"),
         !(timestamp > "2023-08-27 07:56:00" & timestamp < "2023-09-11 16:15:00"),
         !(timestamp > "2023-09-15 04:07:00" & timestamp < "2023-10-19 12:25:00"),
         #!(timestamp > "2023-10-19 11:30:00" & timestamp < "2023-10-19 12:25:00"),
         !(timestamp > "2023-11-08 01:15:00" & timestamp < "2023-11-08 03:00:00"),
         !(timestamp > "2023-12-07 13:50:00" & timestamp < "2023-12-07 15:30:00"),
         !(timestamp > "2023-12-22 11:45:00" & timestamp < "2023-12-22 12:20:00"),
         !(timestamp > "2024-01-28 00:00:00" & timestamp < "2024-02-08 14:00:00"),
         !(timestamp > "2024-02-13 05:00:00" & timestamp < "2024-03-13 22:00:00"),
         !(timestamp > "2024-03-22 12:35:00" & timestamp < "2024-03-22 13:26:00"),
         !(timestamp > "2024-04-01 11:09:00" & timestamp < "2024-04-01 11:20:00"),
         !(timestamp > "2024-06-03 12:50:00" & timestamp < "2024-06-03 13:45:00"),
         !(timestamp > "2024-06-05 14:50:00" & timestamp < "2024-06-05 15:40:00"),
         !(timestamp > "2024-08-27 10:30:00" & timestamp < "2024-08-27 11:35:00"),
         timestamp < "2024-09-27 10:13:00",
         pressure > 0.2,
         pressure < 3,
         temp > 0,
         temp < 30,
         corr1 <= 100,
         corr2 <= 100,
         corr3 <= 100,
         !is.na(u), 
         !is.na(v), 
         !is.na(w), 
         !is.na(corr1), 
         !is.na(corr2), 
         !is.na(corr3), 
         !is.na(amp1), 
         !is.na(amp2), 
         !is.na(amp3), 
         # filter velocities to remove impossible velocities
         u > -10, u < 10,
         v > -10, v < 10,
         w > -2, w < 2,
         pH > 7.18,
         pH < 10,
         ox_umol_l < 450,
         ox_umol_l > 90) |> 
  mutate(ph_counts = if_else(timestamp > "2023-07-21 00:00:00", ph_counts, NA))
```

remove lines with duplicate timestamps

```{r}
ds_filt <- ds_filt |> 
  group_by(timestamp) |> 
  mutate(duplicate = n()) |> 
  filter(duplicate == 1) |> 
  ungroup()
```

# Save data

```{r}
ds_filt |> 
  to_arrow() |> 
  group_by(year = year(timestamp), month = month(timestamp)) |> 
  write_dataset(file.path(data_dir, "lecs_adv_filt.parquet"))
```

```{r}
dbDisconnect(con)
```

