---
title: "LECS OSM 2024 plots"
format: html
editor: source
---

```{r}
library(tidyverse)
library(arrow)
library(dygraphs)
library(patchwork)

lecs_hourly <- open_dataset("data/processed/surface/lecs_adv_data_all_filt_cal_hourly.parquet/")
theme_set(theme_bw())
```


```{r}
lecs_hourly |> 
  select(time, pH) |>
  #filter(time > "2023-10-17 16:00:00") |> 
  collect() |> 
dygraph()
```

```{r}
df <- lecs_hourly |> 
  select(time, temp, pH, DO_percent) |>
  #filter(time > "2023-07-20 22:00:00") |> 
  collect() |> 
  add_row(tibble_row(time = as.POSIXct("2023-09-01 00:00:00"), 
                     temp = NA, pH = NA, DO_percent = NA)) |> 
  add_row(tibble_row(time = as.POSIXct("2023-10-01 00:00:00"), 
                     temp = NA, pH = NA, DO_percent = NA)) |> 
  mutate(pH = replace(pH, time < "2023-07-20 22:00", NA)) |> 
  arrange(time)
```

```{r}
temp <- df |> 
  ggplot(aes(time, temp)) +
  geom_line(color = "red") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_x_datetime(date_breaks = "month") +
  labs(y = "Temp (C)")

ox <- df |> 
  ggplot(aes(time, DO_percent)) +
  geom_line(color = "darkgreen") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_x_datetime(date_breaks = "month") +
  ylab(expression(O[2]*" (%)"))

ph <- df |> 
  ggplot(aes(time, pH)) +
  geom_line(color = "blue") +
  scale_x_datetime(date_breaks = "month",
                   date_labels = "%b %Y") +
  theme(axis.title.x = element_blank()) +
  labs(y = "pH")

temp / ox / ph

ggsave("timeseries.png", width = 16, height = 7, scale = .6)
```

