---
title: "March SeapHOx"
format: html
editor: source
---

```{r}
library(tidyverse)
library(mlabtools)
library(dygraphs)
library(patchwork)
```

```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_122223.csv")
```

```{r}
dygraph(df)
```
```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_20240401.csv")
```

```{r}
dygraph(df)
```
```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_20240621.csv")
```

```{r}
dygraph(df)
```

```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_20240815.csv")
```

```{r}
dygraph(df)
```

```{r}
ph <- df |> 
  select(timestamp, pH) |> 
  ggplot(aes(timestamp, pH)) + 
  geom_line()

sal <- df |> 
  select(timestamp, sal) |> 
  ggplot(aes(timestamp, sal)) + 
  geom_line()

ph / sal
```
```{r}
df |> 
  select(timestamp, pressure) |> 
  dygraph()
```


```{r}
df |> 
  select(timestamp, temp) |> 
  dygraph()
```


```{r}
df |> 
  select(timestamp, oxygen) |> 
  dygraph()
```

```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_20240903.csv")
```

```{r}
dygraph(df)
```
```{r}
df <- read_seaphox("data/SeapHOx Data/Seaphox_LECS_20240917.csv")
```

```{r}
dygraph(df)
```